name: application-docker
services:
  postgres:
    container_name: postgres-container
    image: postgres:18
    mem_limit: 700m
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Syf#20011015#
      POSTGRES_DB: postgres
      TZ: Asia/Shanghai
    volumes:
      - postgres-data:/var/lib/postgresql
    network_mode: "host"
    restart: no
    logging:
      driver: "none"

  redis:
    container_name: redis-container
    image: redis/redis-stack-server:7.4.0-v8
    environment:
      REDIS_ARGS: "--requirepass Syf#20011015# --ignore-warnings ARM64-COW-BUG"
    network_mode: "host"
    restart: no
    logging:
      driver: "none"

  rabbitmq:
    container_name: rabbitmq-container
    image: rabbitmq:4.2.1-management
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: Syf#20011015#
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    network_mode: "host"
    restart: no
    logging:
      driver: "none"

volumes:
  postgres-data:
    name: postgres-data
  rabbitmq-data:
    name: rabbitmq-data
