name: application-docker
services:
  postgres:
    container_name: postgres-container
    image: postgres:18
    mem_limit: 700m
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      application-network:
        ipv4_address: 172.20.0.10
    restart: no

  redis:
    container_name: redis-container
    image: redis/redis-stack-server:7.4.0-v7
    environment:
      REDIS_ARGS: "--requirepass 123456 --ignore-warnings ARM64-COW-BUG"
    ports:
      - "6379:6379"
    networks:
      application-network:
        ipv4_address: 172.20.0.11
    restart: no

  rabbitmq:
    container_name: rabbitmq-container
    image: rabbitmq:4.2.0-rc.1-management
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: 123456
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      application-network:
        ipv4_address: 172.20.0.12
    restart: no

  elasticsearch:
    container_name: elasticsearch-container
    image: elasticsearch:8.18.1
    mem_limit: 1g
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - ELASTIC_PASSWORD=123456
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      application-network:
        ipv4_address: 172.20.0.13
    restart: no

volumes:
  postgres:
    name: postgres_volume
  rabbitmq:
    name: rabbitmq_volume

networks:
  application-network:
    name: application-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
